### PR TITLE
Create blit_saw.cpp blit_square.cpp

### PR DESCRIPTION
**Pull request by fukuroder**

### CODE REVIEW

**Comment by bluecataudio** [comment]
Thanks for the C++ port! Would you mind sharing the XCode / Visual C++ projects or makefile too?

**Comment by fukuroder** [comment]
Thanks. Please confirm the following directory structure.

```
plugnscript
 +--Built-in
 +--Presets
 +--Scripts
 +--Skins
 +--NativeSource
     |  README.TXT
     |
     +--build
     |   +--VS2015
     |       |      blit_saw.sln                 <-new
     |       |      blit_square.sln              <-new
     |       |
     |       +--Projects
     |       |      blit_saw.vcxproj             <-new
     |       |      blit_saw.vcxproj.filters     <-new
     |       |      blit_square.vcxproj          <-new
     |       |      blit_square.vcxproj.filters  <-new
     |       |
     |       +--vsprops
     |              common.props
     |              debug.props
     |              debug.x64.props
     |              debug.x86.props
     |              release.props
     |              release.x64.props
     |              release.x86.props
     |
     +--include
     |      chelpers.h
     |      cpphelpers.h
     |      dspapi.h
     |
     +--src
         +--samples
             +--blit_saw
             |      blit_saw.cpp     <-new
             | 
             +--blit_square
             |      blit_square.cpp  <-new
             |
             +--library
                    BiquadFilter.h
                    Constants.h
                    file.h
                    Midi.h
                    rand.h
                    README.TXT
                    Utils.h
                    WaveFile.h
```

**Comment by bluecataudio** [comment]
Sounds good, indeed!

**Comment by fukuroder** [comment]
Thank you for confirmation. I will commit this structure. Please wait a few days.

**Pull request merged**
